---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/cages":
    get:
      summary: Retrieves all cages
      tags:
      - Cages
      parameters:
      - name: page
        in: query
        description: Page number
        default: 1
        schema:
          type: integer
      - name: items
        in: query
        description: Per page count
        default: 10
        schema:
          type: integer
      - name: offset
        in: query
        description: Offset
        default: 0
        schema:
          type: integer
      responses:
        '200':
          description: List your Jurassic Park Cages
          content:
            application/json:
              examples:
                cages:
                  value:
                  - id: 53
                    name: Herbivores
                    status: closed
                  - id: 54
                    name: Carnivores
                    status: closed
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/cage"
    post:
      summary: Creates a cage
      tags:
      - Cages
      parameters: []
      responses:
        '201':
          description: Cage created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  default: New Cage
                status:
                  type: string
                  default: down
              required:
              - name
  "/cages/{id}":
    get:
      summary: Retrieves a cage
      tags:
      - Cages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Cage found
        '404':
          description: Cage not found
    patch:
      summary: Updates a cage
      tags:
      - Cages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Cage updated
        '404':
          description: cage not found
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  default: Herbivores Cage
                status:
                  type: string
                  default: down
              required:
              - name
    delete:
      summary: Deletes a cage
      tags:
      - Cages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Cage deleted
        '422':
          description: invalid request
        '404':
          description: cage not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    cage:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
      required:
      - id
      - name
